services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-parkiet
    restart: unless-stopped
    environment:
      POSTGRES_DB: parkiet
      POSTGRES_USER: parkiet
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - parkiet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d parkiet"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis-parkiet
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - parkiet-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  parkiet-network:
    driver: bridge
